### ISSUE TITLE
Study registration not working

### ISSUE THREAD

**Issue by amgeronimo** [onnela-lab/beiwe-android#63]
Tried registering a android phone (android version 9) with a new instance of the beiwe2 app.  Cannot advance past the registration screen.  Gives the error "Are you sure the URL for the study is correct? Beiwe cant connect to the server" on the phone.  However, the backend shows than an android phone has registered.  The phone cannot advance past the registration screen.

**Comment by biblicabeebli** [comment]
Looking into it, apologies for the inconvenience - in the meantime check if easy-enrollment (can be enabled on a per-participant or per-study basis in their respective pages) allows registration to work.

Please make sure your Beiwe servers are up to date, I do my best with backwards compatibility but maybe something squeaked by.

(There wasn't any intentional change to registration logic on the 3.4.x update, that error message is fairly specific and relates to network problems so hopefully I can track this down pretty quick.)

**Comment by biblicabeebli** [comment]
Ah, I have worked out the issue.
The error message displayed is incorrect. When you provide a value for the temporary password that does not match the current password on the server it incorrectly displays the bad URL message.  When you get the value correct registration proceeds as expected.  

The registration process could be generally better, we made easy enrollment mode (which disables the temporary code validation at registration entirely) to help streamline enrollment. (Thank you for posting, this explains some glitches we've not been able to explain, and the second enrollment attempt would always work so the issue was never raised back up to me.)

I'll try and fix this - it is probably a backend return-the-correct-error-code issue rather than an app issue, the backend received updates to the registration process a couple months ago. (possibly the addition of easy enrollment, heheh, oops.)

We are planning to clean up enrollment, ideally have a QR code mode, at the very least add a validation field or make the temporary key visible, and get a better way of authenticating the app to the server as there are some desync bugs; make login use any present harware authentication options with an optional pin for both the android and ios apps... but that's not started yet and affects 3 codebases so don't make any plans that depend on it.

**Comment by biblicabeebli** [comment]
Actually it looks like the error message is correct with the current state of the backend code, there was a change in the truly distant when-iOS-was-first-built past to the way errors were detected at registration time, the error message reads:
```Sorry: either your Study URL, your User ID, or your Temporary Password is incorrect.```

When the app can't reach the server at all it displays:
```Are you sure the URL for the study is correct?  Beiwe can't connect to the server.```

**Comment by biblicabeebli** [comment]
(woops double reopened?)

Reopenning issue, I will continue to look into this, I did not replicate that half.

**Comment by biblicabeebli** [comment]
ok, I think we finally had this happen on our server - not positive, but there is a bug with intervention dates.

**Comment by biblicabeebli** [comment]
bug report (internal link just stashing this on the direct issue):
https://onnela-lab.sentry.io/issues/4183280305/?alert_rule_id=213882&alert_timestamp=1684079431465&alert_type=email&project=133863&referrer=alert_email

**Comment by biblicabeebli** [comment]
Hm, the failed registration that produced the bug I saw does not have the falsely registered situation you encountered, it was a different bug.
