### ISSUE TITLE
How to get consistent accelerometer sampling rate on Android devices?

### ISSUE THREAD

**Issue by enwq** [onnela-lab/beiwe-android#85]
Hi! We are trying to collect accelerometer data continuously at 50 Hz on Android devices, but we were unable to achieve this. When the phone was stationary and not being used, the collected data only contained intermittent periods of 50 Hz sampling and gaps without data between them. The sampling rate seemed to be more consistent when the phone was moving. We have disabled battery optimization for the app. Since we can collect at 50Hz all the time on iPhones, I'm wondering if there's any tip to configure the Android device so we can do this as well for Android. Below are details about experiments we ran.

App version: 3.5.11
1. Oneplus 7 Pro, Android 11, left phone stationary and unused overnight
- When the phone was plugged in we can sample at 50 Hz all the time (i.e. closed to 3600 seconds *50 Hz = 180,000 samples every hour)
- When the phone was unplugged if we turned off sleep standby optimization we can sample at 50 Hz most of the time (~170,000 samples per hour).
- When the phone was unplugged and sleep standby optimization turned on it didn't collect any data during this period.
2. Oneplus 7 Pro upgraded to Android 12,  left phone stationary and unused overnight
-  If we plugged the phone in we can still sample at 50 Hz all the time.
-  However when we left the phone unplugged and turned off sleep standby optimization, this time we can no longer continuously sample at 50 Hz (best ~140,000 samples per hour).
3. Samsung Galaxy A14, Android 13, left phone stationary and unused overnight
- This device doesn't have the sleep standby optimization option, but we turned on its adaptive battery function.
- Overnight it only collected no more than 20,000 samples per hour. Often we got 1-2 seconds with 50 Hz then longer periods without any data.

As you can see the behaviors varied across devices and Android versions, do you have any recommendations to configure different Android power saving functions to get as much consistently sampled data as possible? Thank you!!

**Comment by biblicabeebli** [comment]
Thank you for the details.

Fundamentally, we record what the device gives us. If it turns off the sensor then we don't get any data. We don't currently have a mechanism for identifying whether the device stops reporting data, and I don't think there is an API for that. Unfortunately, I can confirm from my own testing that the precision of the frequency parameter passed in to Android's accelerometer api is kinda crap. I found that only had a handful of frequencies would work.

There are some hardcoded options that we used in old versions of the app, before we added selectable frequencies, and we could try enabling that option. However, I think I tested this and I don't think it changed anything.

As for always recording data, we probably don't have settings that are great for that, I assume you are providing custom, and very long, recording durations? Could you tell me what those settings are?

**Comment by biblicabeebli** [comment]
You might as well try setting on time for a million seconds.

Honestly though, consider installing android studio and building the app yourself. I can show you where to change settings related to the acclerometer parameters. iirc my notes on what I saw when adding the ability to select a frequency are in the accelerometer file code.

This does raise the thought that the old mode of selecting frequency rate might have different runtime behavior.

just fyi I can't make this a priority right now, but I am aware that accelerometer has degraded some over the past few releases, and I have not gotten to any Android 14 testing.

**Comment by enwq** [comment]
Okay so I did a bit more testing for setting on duration to a million seconds. The problem is that if I build the app then rebuild it after a short period, accelerometer will not be turned on because it runs into the scenario that sensor defaults to off, and the next turn on period is a million seconds from now (i.e. the case `!is_running && should_turn_on_again_at >= now` in `do_an_on_off_session_check` in `MainService.kt`). My understanding is that this can cause missing data when the user restarts their phone. So in this case if I want continuous sampling should I just disable all the logics related to the on and off duration?

Also, it looks like changing the data collection settings (i.e. on/off duration) on the backend website does not affect data collection for registered users, is this the expected behavior?

**Comment by biblicabeebli** [comment]
https://github.com/onnela-lab/beiwe-android/blob/main/app/src/main/java/org/beiwe/app/listeners/AccelerometerListener.kt

scroll to the big comment at the end, that disorganized ramble were my notes.

We also have had this statement on the study configuration page about Android accelerometer data since around september/october iirc.
<hr>
 Android And Sampling Rates

Values entered for sample rates of the accelerometer are not very reliable. You can and should expect similar behavior with other sensor types. Your experience will vary.

Due to the sheer extent and variation of Android devices - hardware sensors, device manufacturer customization, battery life and power-saving details - our best advice is that you need to test them first. To improve the experience we are working to make these values configurable after a study begins, and may separate out Android's sampling rates from the iOS ones.

Here is an example from our Android developer, run on a Pixel 6 with Android 13:

_Only a handful of real frequencies exist: 1-2ms, 2-3ms, 4-5ms, 8-9ms, 18-19ms, 36-37ms, ~72ms, ~144ms, and ~288ms. The faster time brackets tend to be more reliable, but the mapping of any specific input value to expected output behavior is quite annoying. 9ms results in the 4-5ms frequency, 10ms results in the 8-9ms frequency, and any value above 18ms would mostly run at 18-19ms with occasional jumps to a slower bracket. Sometimes that jump was random, sometimes it coinsided with device usage. 288ms seemed to be a power saving mode._

**Comment by biblicabeebli** [comment]
ok, uh, the last time I loaded this page to add my most recent comment the prior post was from me.

I'll try and get back to you, I don't have the bandwidth right now.

**Comment by biblicabeebli** [comment]
> Also, it looks like changing the data collection settings (i.e. on/off duration) on the backend website does not affect data collection for registered users, is this the expected behavior?

There is an update-settings feature, it restarts the app after downloading and applying any changes.

> My understanding is that this can cause missing data when the user restarts their phone.

At app start (there is a hook to start the service at device boot / just after final unlock) there is a logic check to see what the current state of the timers are, these timers record a timestamp of "next on event" and "next off event".  This works for when the timers are in use, but would probably not be very compatible with very long on durations.  To really change the app to support an always-on data stream probably requires adding new flags (or in your case just hardcode it) to start the accelerometer and periodically check if it is running.

Accelerometer calls `do_an_on_off_session_check` - which is the code that opposes what you are doing by design - from `accelerometer_logic` inside `MainService.kt`.  Your best bet for always-on-ifying it is to update `accelerometer_logic` to just check if the accelerometer is on, and if not then turn it on.

It `AccelerometerListener.kt` sets its own boolean of whether it is enabled, so you may need to go in and write code to check whether the sensor is _actually running_ to allow the app to recover.  If you do that please let me know because that seems like undesireable behavior tbh.

**Comment by enwq** [comment]
Excuse me for the question but where exactly can I find this update-settings feature? I couldn't find it in the app.

**Comment by biblicabeebli** [comment]
It's the second large function in this file.

https://github.com/onnela-lab/beiwe-android/blob/main/app/src/main/java/org/beiwe/app/storage/SetDeviceSettings.kt

**Comment by enwq** [comment]
> FYI in case you haven't encountered it, at least if memory serves, some android devices turn off accelerometer entirely when the screen is off, some rate limit, and some don't care. I've seen all three.

This is exactly the problem I got. In my testing the Samsung device seemed to be pretty bad, while Pixel phones tended to have consistent sampling rate all the time. So in this case I guess there isn't anything we can do control the accelerometer behavior?

**Comment by biblicabeebli** [comment]
Here's 15 minutes of brainstorming, I do not know the answer, you will have to do research. If you find an answer, please report in because this is a problem with the platform that we have not resolved.  It is equally helpful if you can report anything that definitely doesn't work. I have not done the research on it in several years now. 

You could try playing with wake locks, we never went that far.

You could try identifying exactly what sleep mode actually applies the rate change, see if it's not actually "turning the screen off", maybe there's a way to disable that sleep mode entirely.

on iOS they just added (iOS 17) something called health research background tasks. These are transparently perfect for beiwe's use case (I'm a struggling to get them working), so we should check if there is an android platform equivalent.

I don't believe there are any permissions for it specifically, but since we have delisted from the Google Play store in August there may be permissions options that play store apps were not allowed to have enabled.

I guess you could try rooting the phone and seeing what happens? Obviously that's "a bit much."

Maybe there's a difference between _locking_ the phone and turning the screen off that we never investigated? 

You could try cranking up the GPS and location service usage. It could be the case that sensor input is linked somehow. I don't think android actually works this way, but this is what we've had to do on the iOS app (at least until I get background health research tasks working for users on ios 17).

… Lock screen widget?

Is there an API for those low power "keep a small portion of the screen enabled so that the clock is always visible" - Things?

**Comment by biblicabeebli** [comment]
Wondering if you have any progress to report after my novella there....
